<template>
    <v-btn color="red" @click="clearLocalStorage">
        Clear {{ vars.length == 0 ? "EVERY SINGLE THING" : "" }} localStorage
    </v-btn>
</template>

<script>
export default {
    methods: {
        clearLocalStorage() {
            if (this.vars.length > 0) {
                this.vars.forEach((item) => {
                    localStorage.removeItem(item);
                    console.log(`Removed ${item} from localStorage`);
                });
            } else {
                localStorage.clear();
                console.log('Cleared all localStorage');
            }
        },
    },
};
// Generated by Copilot
</script>